# ChatColor Plugin Configuration
# This file defines available colors and gradients for chat and name colors

save_interval: 300
auto_save: true

# Simple colors using Minecraft color codes
simple_colors:
  red: "§c"
  dark_red: "§4"
  blue: "§9"
  dark_blue: "§1"
  green: "§a"
  dark_green: "§2"
  yellow: "§e"
  gold: "§6"
  purple: "§5"
  light_purple: "§d"
  aqua: "§b"
  dark_aqua: "§3"
  white: "§f"
  gray: "§7"
  dark_gray: "§8"
  black: "§0"

# Gradient configurations using HSV or RGB interpolation
gradients:
  # Rainbow gradient using HSV
  rainbow:
    type: "hsv"
    start_hue: 0.0
    end_hue: 360.0
    saturation: 1.0
    value: 1.0

  # Fire gradient using RGB interpolation
  fire:
    type: "rgb"
    colors:
      - [255, 0, 0]    # Red
      - [255, 165, 0]  # Orange
      - [255, 255, 0]  # Yellow

  # Ocean gradient
  ocean:
    type: "rgb"
    colors:
      - [0, 119, 190]   # Deep blue
      - [0, 191, 255]   # Sky blue
      - [135, 206, 235] # Light blue

  # Sunset gradient
  sunset:
    type: "rgb"
    colors:
      - [255, 69, 0]    # Red-orange
      - [255, 140, 0]   # Dark orange
      - [255, 215, 0]   # Gold
      - [255, 20, 147]  # Deep pink

  # Forest gradient
  forest:
    type: "rgb"
    colors:
      - [34, 139, 34]   # Forest green
      - [50, 205, 50]   # Lime green
      - [144, 238, 144] # Light green

# Plugin settings
settings:
  # Default colors for new players
  default_chat_color: "white"
  default_name_color: "white" 